// Mock data for MonsoonShield demo
// In production, all data comes from real APIs (IMD, CWC, IDSP, Google Maps)

export const MOCK_ALERTS = [
  {
    id: "alert-1",
    type: "flood",
    severity: "warning",
    title: "Heavy Rainfall Warning",
    titleHi: "भारी वर्षा की चेतावनी",
    description: "IMD has issued Orange Alert for heavy to very heavy rainfall in your district. River levels rising.",
    area: "Pune District, Maharashtra",
    source: "IMD",
    validUntil: "2026-07-12T18:00:00Z",
    issuedAt: "2026-07-11T06:00:00Z",
    color: "amber",
    actionRequired: "Avoid low-lying areas. Keep emergency kit ready. Monitor updates every 15 minutes.",
  },
  {
    id: "alert-2",
    type: "health",
    severity: "watch",
    title: "Dengue Risk Alert",
    titleHi: "डेंगू जोखिम चेतावनी",
    description: "Rising dengue cases detected in 3 wards. Eliminate stagnant water around your home.",
    area: "Urban Areas — Pune",
    source: "IDSP / Municipal Health",
    validUntil: "2026-07-20T00:00:00Z",
    issuedAt: "2026-07-10T09:00:00Z",
    color: "orange",
    actionRequired: "Remove standing water. Use mosquito repellent. Report fever cases to ward health officer.",
  },
  {
    id: "alert-3",
    type: "road",
    severity: "info",
    title: "Road Blockage — NH48",
    titleHi: "सड़क अवरोध — NH48",
    description: "Waterlogging reported on NH48 near Wakad. Use alternate route via Baner Road.",
    area: "Pune-Mumbai Expressway (NH48)",
    source: "Community Report (Verified)",
    validUntil: "2026-07-11T20:00:00Z",
    issuedAt: "2026-07-11T05:30:00Z",
    color: "blue",
    actionRequired: "Use Baner Road or Hinjewadi Road as alternate. Expect 30-45 min delay.",
  },
];

export const MOCK_WEATHER = {
  current: {
    temp: 24,
    feelsLike: 27,
    humidity: 89,
    rainfall24h: 68,
    windSpeed: 22,
    visibility: 4,
    condition: "Heavy Rain",
    conditionHi: "भारी बारिश",
    description: "IMD Orange Alert active. Heavy rainfall expected through midnight.",
  },
  hourly: [
    { time: "Now", rain: 68, temp: 24 },
    { time: "3 PM", rain: 82, temp: 23 },
    { time: "6 PM", rain: 91, temp: 22 },
    { time: "9 PM", rain: 45, temp: 22 },
    { time: "12 AM", rain: 30, temp: 21 },
    { time: "3 AM", rain: 15, temp: 20 },
    { time: "6 AM", rain: 22, temp: 21 },
    { time: "9 AM", rain: 55, temp: 23 },
  ],
  forecast: [
    { day: "Today", high: 25, low: 20, rain: 85, condition: "Heavy Rain", icon: "🌧️" },
    { day: "Sat", high: 26, low: 21, rain: 70, condition: "Rain", icon: "🌧️" },
    { day: "Sun", high: 27, low: 22, rain: 45, condition: "Partly Cloudy", icon: "⛅" },
    { day: "Mon", high: 28, low: 23, rain: 30, condition: "Cloudy", icon: "🌥️" },
    { day: "Tue", high: 29, low: 23, rain: 60, condition: "Rain", icon: "🌧️" },
    { day: "Wed", high: 27, low: 22, rain: 80, condition: "Heavy Rain", icon: "⛈️" },
    { day: "Thu", high: 26, low: 21, rain: 75, condition: "Rain", icon: "🌧️" },
  ],
};

export const MOCK_SHELTERS = [
  {
    id: "shelter-1",
    name: "Government High School No. 5",
    address: "Plot 45, Ring Road, Shivajinagar",
    lat: 18.5204,
    lng: 73.8567,
    capacity: 600,
    currentOccupancy: 427,
    status: "open",
    amenities: { water: true, food: true, medical: true, toilets: true, power: true, wifi: false },
    petFriendly: false,
    wheelchairAccessible: true,
    womensSection: true,
    contact: "020-12345678",
    managedBy: "District Administration",
    distanceKm: 1.2,
    lastUpdated: "10 min ago",
  },
  {
    id: "shelter-2",
    name: "Community Hall Sector 7",
    address: "Sector 7, Hinjewadi Phase 1",
    lat: 18.5894,
    lng: 73.7397,
    capacity: 400,
    currentOccupancy: 283,
    status: "open",
    amenities: { water: true, food: true, medical: false, toilets: true, power: true, wifi: true },
    petFriendly: true,
    wheelchairAccessible: true,
    womensSection: true,
    contact: "020-87654321",
    managedBy: "NGO — Goonj Pune Chapter",
    distanceKm: 2.1,
    lastUpdated: "5 min ago",
  },
  {
    id: "shelter-3",
    name: "Municipal Corporation Annex Building",
    address: "Deccan Gymkhana, Pune",
    lat: 18.5167,
    lng: 73.8428,
    capacity: 300,
    currentOccupancy: 89,
    status: "open",
    amenities: { water: true, food: true, medical: true, toilets: true, power: true, wifi: true },
    petFriendly: false,
    wheelchairAccessible: true,
    womensSection: true,
    contact: "020-11223344",
    managedBy: "Pune Municipal Corporation",
    distanceKm: 3.4,
    lastUpdated: "2 min ago",
  },
  {
    id: "shelter-4",
    name: "Bal Gandharva Rang Mandir",
    address: "Near Balgandharva Bridge, Jangli Maharaj Road",
    lat: 18.5236,
    lng: 73.8560,
    capacity: 800,
    currentOccupancy: 610,
    status: "almost-full",
    amenities: { water: true, food: true, medical: true, toilets: true, power: true, wifi: false },
    petFriendly: false,
    wheelchairAccessible: false,
    womensSection: true,
    contact: "020-55667788",
    managedBy: "SDRF Maharashtra",
    distanceKm: 4.8,
    lastUpdated: "15 min ago",
  },
];

export const MOCK_COMMUNITY_REPORTS = [
  {
    id: "rep-1",
    type: "road_blocked",
    title: "NH48 waterlogging near Wakad",
    description: "Water is knee-deep. Buses can't pass. Use Baner Road.",
    reporter: "Rahul M.",
    lat: 18.5942,
    lng: 73.7623,
    upvotes: 47,
    verified: true,
    timestamp: "45 min ago",
    photo: true,
  },
  {
    id: "rep-2",
    type: "flood_warning",
    title: "Mula river water level rising fast",
    description: "River is 2m above normal. Nashik road area residents should be alert.",
    reporter: "Priya S.",
    lat: 18.5314,
    lng: 73.8446,
    upvotes: 89,
    verified: true,
    timestamp: "1 hr ago",
    photo: true,
  },
  {
    id: "rep-3",
    type: "need_help",
    title: "Elderly couple stranded — Bibwewadi",
    description: "My 70-year-old parents are stuck on ground floor. Need evacuation help.",
    reporter: "Anonymous",
    lat: 18.4907,
    lng: 73.8597,
    upvotes: 23,
    verified: false,
    timestamp: "20 min ago",
    photo: false,
    urgent: true,
  },
  {
    id: "rep-4",
    type: "resource_available",
    title: "Free hot meals — Katraj Gurdwara",
    description: "Gurudwara langar distributing free meals. Capacity: 500 people. Open 24 hours.",
    reporter: "Gurpreet Singh",
    lat: 18.4579,
    lng: 73.8612,
    upvotes: 134,
    verified: true,
    timestamp: "2 hrs ago",
    photo: true,
  },
];

export const MOCK_FLOOD_PREDICTION = [
  { time: "6 AM", level: 42, danger: 60 },
  { time: "9 AM", level: 55, danger: 60 },
  { time: "12 PM", level: 68, danger: 60 },
  { time: "3 PM", level: 81, danger: 60 },
  { time: "6 PM", level: 88, danger: 60 },
  { time: "9 PM", level: 76, danger: 60 },
  { time: "12 AM", level: 62, danger: 60 },
  { time: "3 AM", level: 51, danger: 60 },
  { time: "6 AM+1", level: 45, danger: 60 },
];

export const MOCK_VOLUNTEERS = [
  { id: "v1", name: "Ananya K.", skills: ["First Aid", "Boat Operator"], available: true, distance: "0.8 km" },
  { id: "v2", name: "Rajan M.", skills: ["Medical Professional", "Hindi/Marathi"], available: true, distance: "1.2 km" },
  { id: "v3", name: "Sana B.", skills: ["Social Work", "Urdu/Hindi"], available: false, distance: "2.1 km" },
  { id: "v4", name: "Deepak P.", skills: ["Construction", "Heavy Vehicle"], available: true, distance: "3.0 km" },
];

export const RISK_SCORE_FACTORS = [
  { label: "Location (Flood Zone)", score: 75, weight: 0.30 },
  { label: "Home Type (Ground Floor)", score: 80, weight: 0.20 },
  { label: "Current Rainfall", score: 68, weight: 0.10 },
  { label: "River Level", score: 82, weight: 0.15 },
  { label: "Preparedness Level", score: 35, weight: 0.15 },
  { label: "Household Vulnerability", score: 50, weight: 0.10 },
];
